require 'lib/fibonacci_matrix'

class Problem2
  attr_reader :description

   def initialize
    @description = <<-EOS
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not exceed four million.
    EOS
  end

  def get_answer
    i = 0
    sum = 0
    while true do
      i += 1
      break if (f = fib(i)) >= 4_000_000
      sum += f if f % 2 == 0
    end

    sum
  end
end